// This file was generated by Prisma, but is not needed since we use default paths.
// Vercel type checker fails to find @prisma/config if it's not installed.
// import "dotenv/config";
// import { defineConfig } from "@prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });
